### ISSUE TITLE
Katoolin-Robust wont install wifi tools

### ISSUE THREAD

**Issue by pcfreaxx** [mkrupczak3/Katoolin-Robust#2]
trying to install ALL wifi tools in one step (0).

choosing "0" shows this error: 

						
Insert the number of the tool to install it .

kat > 0
sh: 1: Syntax error: word unexpected (expecting "do")
`

**Comment by mkrupczak3** [comment]
Oh, I probably messed up the syntax for the Wi-Fi tools installation. Does it work for you with any other tools?

The commit history should show the changes I've made. Probably near "opcion 2 == 0" and the Wi-Fi stuff I've made a syntax error.

It may take me a bit before I can get to a computer to fix this, but I can accept a PR from my phone if it comes. Otherwise  I'll try and take a look later

**Comment by mkrupczak3** [comment]
May have been resolved in #3, but not yet tested.

**Comment by pcfreaxx** [comment]
Good Morning. I have tested section wifi-tools . Now anything happens if i choose 0. i try to compare last wifi tool syntax with a working section, but i am totally new in this stuff.

**Comment by mkrupczak3** [comment]
Oh cool, so it works at least a bit?

**Comment by pcfreaxx** [comment]
yeah in main menu is 0 working to install most of the tools. great. i have started learning python for better understanding. educational profits :)
only teardrop is, to follow now the process of installation, when you install the whole suite at once. i think it would better to install one category in one step. very interesting coding with python.

**Comment by mkrupczak3** [comment]
Yeah, python's a great language to know. The lack of brackets messes me up sometimes though. 

This book might help you get started (a lot of the beginning chapters were review from school for me, but is great if you're just getting started):

https://github.com/halterman/PythonBook-SourceCode
